# Generated by Django 5.1.2 on 2025-04-10 14:25

import config.utils.image_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_rename_active_categoryimage_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryimage',
            name='image',
            field=models.ImageField(upload_to='categories/', validators=[config.utils.image_validators.validate_image_size, config.utils.image_validators.validate_image_resolution]),
        ),
    ]
